name: Ephemeral Issue Comment

on:
  issue_comment:
    types:
      - created
      - edited
concurrency:
  group: eph-webapp-${{ github.ref }}
  cancel-in-progress: false
jobs:
  pr_commented:
    name: PR comment
    if: contains(github.event.issue.labels.*.name, 'ephemeral') && contains(github.event.comment.body, '/set_var')
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - env:
          BODY: ${{ github.event.comment.body }}
        run: |
          envs=''
          echo "$BODY" | while read line ; do
            if [[ $line == "/set_var"* ]]; then
              ps=( $(echo "$line" | tr '\n' ' ') ) 
              key=${ps[2]}
              value=${ps[3]}
              if [[ -n "$key" ]] && [[ -n "value" ]]; then
                if [ -n "$envs" ]; then
                  envs="$envs,"
                fi
                envs="$envs$key=$value"
              fi
            fi
          done
          echo ENVS=$envs >> $GITHUB_ENV
    outputs:
      overrides: ${{ env.ENVS }}
  deploy:
    needs: [pr_commented]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.pr_commented.outputs.overrides }}
